module.exports = () => [
    { domain: "westeurope", url: "https://dev.azure.com/janono-pub/f3f76e44-c0c5-43a1-8ffb-6fd53baeb8f0/_apis/git/repositories/4a9f397c-2857-4ec9-a434-726ef0414ea1/items?path=/src/westeurope.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&api-version=5.0", name: "ADO West Europ", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/nl.svg", icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "southeastasia", url: "https://dev.azure.com/speedASe/ec0ed821-d9e9-46a4-89e1-034a43c03b28/_apis/git/repositories/5ba74da3-843f-45f4-80b8-5ce69b2115ca/items?path=/src/southeastasia.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&api-version=5.0", name: "ADO Southeast Asia", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/sg.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "australiaeast", url: "https://dev.azure.com/speedAUe/1b125322-f16b-4bda-b4d3-bb269c71fa1c/_apis/git/repositories/b46cfa67-b09a-4f39-865a-d07d38dff0b2/items?path=/src/australiaeast.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&api-version=5.0", name: "ADO Australia East", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/au.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "uksouth", url: "https://dev.azure.com/speedUKs/67559a37-8e94-4bbf-8cb2-ae60a6490a9e/_apis/git/repositories/27863565-9557-4306-bbdc-2ad1b8d333f5/items?path=/src/uksouth.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&api-version=5.0", name: "ADO UK South", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "brazilsouth", url: "https://dev.azure.com/speedBRs/632bc85b-7173-4b8b-a564-426d038f5b9e/_apis/git/repositories/727f72c5-eb40-46f1-a8ea-72b9114c56b4/items?path=/src/brazilsouth.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&api-version=5.0", name: "ADO Brazil South", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/br.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "eastus2", url: "https://dev.azure.com/speedusc/234a8c55-07ad-4de2-abdd-55a2584959b3/_apis/git/repositories/bad1fd3e-69b6-4ac8-a629-5a8ce4a3a91f/items?path=/src/eastus2.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&api-version=5.0", name: "ADO East US 2", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "canadacentral", url: "https://dev.azure.com/speedCAc/d47254a2-dbc1-4ff3-9d1c-0e483474c105/_apis/git/repositories/73d2d8cb-53cf-4315-9dea-4e80fb5261e5/items?path=/src/canadacentral.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&api-version=5.0", name: "ADO Canada Central", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ca.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "southindia", url: "https://dev.azure.com/speedINs/d2fe9c98-cfff-4bce-9a5f-ec54e927816a/_apis/git/repositories/57b0275a-1c93-44ba-8b98-188cf1783564/items?path=/src/southindia.json&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=main&resolveLfs=true&api-version=5.0", name: "ADO South India", icon2: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/in.svg" , icon: "https://raw.githubusercontent.com/Azure4DevOps/Azure-Icons/master/Azure_Public_Service_Icons_V6/Icons/devops/10261-icon-service-Azure-DevOps.svg"},
    { domain: "github", url: "https://raw.githubusercontent.com/JanuszNowak/speed/master/src/github.json", name: "GitHub", icon: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" }
];
